version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
      - image: cimg/redis:6.2.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt pytest flask-socketio
      - run:
          name: Run tests
          command: pytest .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

