version: 2.1

executors:
  python-executor:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/python:<< parameters.version >>
      - image: cimg/redis:6.2.6

jobs:
  build:
    executor:
      name: python-executor
      version: << matrix.python_version >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt pytest flask-socketio
      - run:
          name: Run tests
          command: pytest .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          matrix:
            parameters:
              python_version: ["3.8", "3.9", "3.10", "3.11"]
